B1
ProdyusO/Homework4 pull request #9
Opened 2021-06-17 13:31 UTC by ProdyusO

2021-06-17 13:33 UTC, ProdyusO commented
Дмитрий не все ошибки флейка удалось устранитьб в часности  "   I202 Additional newline in a group of imports. 'from groups.utils import format_records' is identified as Third Party and 'from groups.models import Group' is identified as Third Party. 

Спасибо, с уважением Алексей

2021-06-18 12:20 UTC, dbradul requested changes
> I202

Алексей, убадитесь, что импорты сгруппированы в таком порядке

1.standard library imports
2.related third party imports
3.local application/library specific imports

Между каждой группой должна быть пустая строка, а внутри группы пустых строк не должно быть.

2021-06-18 12:20 UTC, dbradul commented on groups/views.py
> +    form = GroupCreateForm(data=request.GET)
Это окончательная версия функции? Не похоже, что она правильная.

2021-06-18 12:20 UTC, dbradul commented on teachers/views.py
> +def create_teacher(request):
см. выше про `create_group`

2021-06-18 12:22 UTC, dbradul commented
И не вижу чтобы установка debug-toolbar'a была завершена.

2021-06-19 15:27 UTC, closed without merging